name: Build Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install  # Adjust based on your project

      - name: Build
        run: |
          npm run build  # Adjust based on your build script

      - name: Upload Build Artifacts (Double-check name & path)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts  # Ensure this matches the download name
          path: out  # Verify the directory containing build artifacts

  analysis:  # Downloads artifacts for analysis (Consider using conditional steps)
    runs-on: ubuntu-latest
    needs: build  # Analysis depends on successful build

    steps:
      - uses: actions/checkout@v3

      - name: Download Test Results (Verify name & path)
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts  # Matches upload name
          path: out  # Download location within the workspace

      - name: Analyze Test Results (Use downloaded artifacts)
        run: echo "Analyzing downloaded build artifacts from 'out' directory..."
