name: Build Workflow

on:
  push:
    branches:
      - main # Set your main branch here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js environment # Adjust this based on your project requirements
        uses: actions/setup-node@v2
        with:
          node-version: "20" # Adjust to your Node.js version

      - name: Install dependencies
        run: npm install # Adjust this based on your project's package manager (npm, yarn, etc.)

      - name: Build
        run: |
          npm run build  # Adjust this based on your build script or command

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build-artifacts
          path: dist # Adjust this to the directory containing your build artifacts
