name: Build and Download Next.js Artifacts
on:
  push:
    branches: [ main ]
jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js and npm
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # You can specify any Node.js version you need
      - name: Install dependencies
        run: npm install  # Or yarn install, depending on your project setup
      - name: Build Next.js App
        run: npm run build  # Or yarn build, depending on your project setup
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: nextjs-build
          path: .next
  download-artifacts:  # Uncomment to download artifacts in a separate job
    runs-on: ubuntu-latest
    needs: build-and-upload  # This job depends on the previous job completing successfully
    steps:
      - uses: actions/checkout@v3
      - name: Download Next.js Artifacts
        uses: actions/download-artifact@v3
        with:
          name: nextjs-build
          path: downloaded-nextjs-build
      - name: Use Downloaded Artifacts (replace with your usage steps)
        run: |  # Example usage (adjust based on your needs)
          cd downloaded-nextjs-build
          # Perform actions on the downloaded Next.js code (e.g., deploy to a server)
