name: Build Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install  # Adjust based on your project

      - name: Build
        run: |
          npm run build  # Adjust based on your build script

      - name: Upload Build Artifacts (Double-check name & path)
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts  # Ensure this matches the download name
          path: out  # Verify the directory containing build artifacts

  release:
      runs-on: ubuntu-latest
      permissions:
        contents: write
        
      needs: build

      steps: 
        - uses: actions/download-artifact@v3
          with:
            name: build-artifacts
            path: out
        - run: zip -r out.zip out/
        - uses: ncipollo/release-action@v1
          with:
            artifacts: "out.zip"
